name: Run Tests

on:
    push:
        branches:
            - master
            - "feature/*" # Adjust as needed for your branches
    pull_request:
        branches:
            - master
            - "feature/*" # Adjust as needed for your branches
    # You can add other events if needed, such as schedule

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "20" # Adjust the Node.js version as needed

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test && npm typecheck && npm lint # Adjust if your test script is named differently
